language: php

php:
  - 7.4

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
  - vendor/bin/phpcs --standard=PSR1 src
  - vendor/bin/phpcs --standard=PSR12 src

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
  # or enable logging
  - travis_retry php vendor/bin/php-coveralls -v